log_format npmplus_geo '[$time_local] [Client $remote_addr] [$geoip2_data_country_code] [$host] "$request" $status $request_time $upstream_response_time "$http_referer" $body_bytes_sent "$http_user_agent"';

access_log /data/nginx/logs/access.log npmplus_geo;
