# --- CONNEXION QBITTORRENT ---
qbt:
  host: "http://gluetun:8080"
  user: "lego"
  pass: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# --- REPERTOIRES DU DISQUE ---
directory:
  root_dir: "/HDD1/downloads"
  remote_dir: "/HDD1/downloads"
  recycle_bin: "/HDD1/downloads/.RecycleBin"
  cross_seed: "/HDD1/downloads/cross-seed"

# --- CORBEILLE DE SÉCURITÉ (15 Jours) ---
recyclebin:
  enabled: true
  empty_after_x_days: 15
  save_torrents: false
  split_by_category: false

# --- REGLAGES DE SECURITE ET TAGS ---
settings:
  force_auto_tmm: false
  tracker_error_tag: "issue"
  nohardlinks_tag: "noHL"
  stalled_tag: "stalled"
  private_tag: "private"

# --- COMMANDES D'EXECUTION AUTOMATIQUE ---
commands:
  recheck: true          # Re-vérifie et relance automatiquement les torrents arrêtés
  share_limits: true     # Applique les limites de ratio et de temps de seed
  tag_update: false      # 🚫 Pas de création automatique de tags par tracker

# --- CATÉGORIES ET DOSSIERS ---
cat:
  "cross-seed": "/HDD1/downloads/cross-seed"

# --- REGLES DE SEED SPÉCIFIQUES POUR CROSS-SEED ---
share_limits:
  cross_seed_limits:
    priority: 1
    add_group_to_tag: false    # 🚫 Pas de tag générique de limite de seed
    categories:
      - "cross-seed"
    include_any_tags:
      - "cross-seed"
    max_ratio: 20              # Ratio Max: 20
    max_seeding_time: 131400   # 131400 minutes = 3 mois exacts
    cleanup: true              # Supprime le torrent et envoie les fichiers à la corbeille pendant 15 jours
