geoip2 /data/goaccess/geoip/GeoLite2-Country.mmdb {
    auto_reload 60m;
    $geoip2_data_country_code source=$realip_remote_addr country iso_code;
}

map $geoip2_data_country_code $allowed_country {
    default 0;

    ""      1;
    "--"    1;

    # North America
    "US"    1;
    "CA"    1;
    "MX"    1;

    # Europe
    "FR"    1;
    "BE"    1;
    "NL"    1;
    "LU"    1;
    "MC"    1;
    "GB"    1;
    "IE"    1;
    "IM"    1;
    "JE"    1;
    "GG"    1;
    "DE"    1;
    "AT"    1;
    "CH"    1;
    "LI"    1;
    "ES"    1;
    "PT"    1;
    "IT"    1;
    "AD"    1;
    "SM"    1;
    "VA"    1;
    "MT"    1;
    "GR"    1;
    "CY"    1;
    "GI"    1;
    "DK"    1;
    "SE"    1;
    "NO"    1;
    "FI"    1;
    "IS"    1;
    "FO"    1;
    "GL"    1;
    "EE"    1;
    "LV"    1;
    "LT"    1;
    "PL"    1;
    "CZ"    1;
    "SK"    1;
    "HU"    1;
    "RO"    1;
    "BG"    1;
    "HR"    1;
    "SI"    1;
    "RS"    1;
    "BA"    1;
    "ME"    1;
    "MK"    1;
    "AL"    1;
    "MD"    1;
    "UA"    1;
}
